### ISSUE TITLE
ENOENT: no such file or directory, scandir...node_modules/babel-istanbul/lib/assets'

### ISSUE THREAD

**Issue by FJunior225** [jmcriffey/babel-istanbul#78]
```
/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mock-fs/node/fs-6.3.0.js:909
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir '/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/assets'
    at Error (native)
    at Object.fs.readdirSync (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mock-fs/node/fs-6.3.0.js:909:18)
    at Object.readdirSync (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mock-fs/lib/index.js:59:31)
    at copyAssets (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/report/html.js:543:20)
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/report/html.js:562:13
    at Array.forEach (native)
    at HtmlReport.writeReport (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/report/html.js:561:26)
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/reporter.js:93:20
    at Array.forEach (native)
    at Object.write (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/reporter.js:87:30)
    at process.<anonymous> (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/command/common/run-with-cover.js:256:30)
    at process.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.emit (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/source-map-support/source-map-support.js:423:21)
    at process.exit (internal/process.js:146:15)
    at done (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mocha/bin/_mocha:474:15)
    at afterWrite (_stream_writable.js:387:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This error occurs when it gets the to end of running our test coverage and trying to print the coverage summary. It started to occur when I upgraded snyk to its latest version via `yarn upgrade snyk`. This resulted in updating qs in the yarn.lock file. I'm not sure the connection to mockFs and why this error is occurring.

Is there supposed to be an assets directory?

I have even tried to remove babel-istanbul and re-add it, however, I am not entirely sure it is babel-istanbul that is causing the error. I think it is mockFs, but unsure what direction to head in. 

Any help would be appreciated.

**Comment by FJunior225** [comment]
Figured out my .yarnclean was removing assets directories
